const states = [
  {
    name: 'Abia',
    capital: 'Umuahia',
    divisions: [
      'Aba North',
      'Aba South',
      'Arochukwu',
      'Bende, Abia',
      'Ikwuano',
      'Isiala Ngwa North',
      'Isiala Ngwa South',
      'Isuikwuato',
      'Ohafia',
      'Osisioma Ngwa',
      'Ugwunagbo',
      'Ukwa East',
      'Ukwa West',
      'Umu Nneochi',
      'Umuahia North',
      'Umuahia South',
      'Obi Ngwa'
    ]
  },
  {
    name: 'Adamawa',
    capital: 'Yola',
    divisions: [
      'Demsa',
      'Fufore',
      'Ganye',
      'Gayuk',
      'Girei',
      'Gombi',
      'Guyuk, Nigeria',
      'Jada, Adamawa',
      'Lamurde',
      'Madagali',
      'Maiha',
      'Mayo Belwa',
      'Michika',
      'Mubi North',
      'Mubi South',
      'Numan, Nigeria',
      'Shelleng',
      'Song, Nigeria',
      'Toungo, Nigeria',
      'Yola North',
      'Yola South',
      'Hung'
    ]
  },
  {
    name: 'Akwa Ibom',
    capital: 'Uyo',
    divisions: [
      'Abak',
      'Eastern Obolo',
      'Eket',
      'Esit Eket',
      'Essien Udim',
      'Etim Ekpo',
      'Etinan',
      'Ibeno',
      'Ibesikpo Asutan',
      'Ibiono-Ibom',
      'Ika, Akwa Ibom',
      'Ikono',
      'Ikot Ekpene',
      'Ikot-Abasi',
      'Ini, Akwa Ibom',
      'Itu, Akwa Ibom',
      'Mbo, Akwa Ibom',
      'Mkpat-Enin',
      'Nsit-Atai',
      'Nsit-Ibom',
      'Nsit-Ubium',
      'Obot-Akara',
      'Okobo, Akwa Ibom',
      'Onna',
      'Oron, Akwa Ibom',
      'Oruk Anam',
      'Udung-Uko',
      'Ukanafun',
      'Uruan',
      'Urue-Offong/Oruko',
      'Uyo'
    ]
  },
  {
    name: 'Anambra',
    capital: 'Awka',
    divisions: [
      'Aguata',
      'Anambra East',
      'Anambra West',
      'Anaocha',
      'Awka North',
      'Awka South',
      'Ayamelum',
      'Dunukofia',
      'Ekwusigo',
      'Idemili North',
      'Idemili South',
      'Ihiala',
      'Njikoka',
      'Nnewi North',
      'Nnewi South',
      'Ogbaru',
      'Onitsha North',
      'Onitsha South',
      'Orumba North',
      'Orumba South',
      'Oyi'
    ]
  },
  {
    name: 'Bauchi',
    capital: 'Bauchi',
    divisions: [
      'Alkaleri',
      'Bauchi',
      'Bogoro',
      'Damban',
      'Darazo',
      'Dass, Nigeria',
      'Gamawa',
      'Ganjuwa',
      'Giade',
      'Itas/Gadau',
      "Jama'are",
      'Katagum',
      'Kirfi',
      'Misau',
      'Ningi, Nigeria',
      'Shira, Nigeria',
      'Tafawa Balewa, Bauchi',
      'Toro, Nigeria',
      'Warji',
      'Zaki, Nigeria'
    ]
  },
  {
    name: 'Bayelsa',
    capital: 'Yenagoa',
    divisions: [
      'Brass, Nigeria',
      'Ekeremor',
      'Kolokuma/Opokuma',
      'Nembe',
      'Ogbia',
      'Sagbama',
      'Southern Ijaw',
      'Yenagoa'
    ]
  },
  {
    name: 'Benue',
    capital: 'Makurdi',
    divisions: [
      'Ado, Benue',
      'Agatu',
      'Apa, Nigeria',
      'Buruku',
      'Gboko',
      'Guma, Nigeria',
      'Gwer East',
      'Gwer West',
      'Katsina-Ala',
      'Konshisha',
      'Kwande',
      'Logo, Nigeria',
      'Makurdi',
      'Obi, Nigeria',
      'Ogbadibo',
      'Ohimini',
      'Oju, Nigeria',
      'Okpokwu',
      'Otukpo',
      'Tarka, Nigeria',
      'Ukum',
      'Ushongo',
      'Vandeikya'
    ]
  },
  {
    name: 'Borno',
    capital: 'Maiduguri',
    divisions: [
      'Abadam',
      'Askira/Uba',
      'Bama, Borno',
      'Bayo, Nigeria',
      'Biu, Nigeria',
      'Chibok',
      'Damboa',
      'Dikwa',
      'Gubio',
      'Guzamala',
      'Gwoza',
      'Hawul',
      'Jere, Borno',
      'Kaga, Nigeria',
      'Kala/Balge',
      'Kukawa',
      'Kwaya Kusar',
      'Mafa',
      'Magumeri',
      'Maiduguri',
      'Marte, Borno',
      'Mobbar',
      'Monguno',
      'Ngala',
      'Nganzai',
      'Shani, Nigeria'
    ]
  },
  {
    name: 'Cross River',
    capital: 'Calabar',
    divisions: [
      'Abia',
      'Akampa',
      'Akpabuyo',
      'Bakassi',
      'Bekwara',
      'Biase',
      'Boki',
      'Calabar South',
      'Etung',
      'Ikom',
      'Obanliku',
      'Obubra',
      'Obudu',
      'Odukpani',
      'Ogoja',
      'Ugep North',
      'Yala',
      'Yarkur'
    ]
  },
  {
    name: 'Delta',
    capital: 'Asaba',
    divisions: [
      'Aniocha South',
      'Anioha',
      'Bomadi',
      'Burutu',
      'Ethiope west',
      'Ethiope east',
      'Ika south',
      'Ika north east',
      'Isoko south',
      'Isoko north',
      'Ndokwa east',
      'Ndokwa west',
      'Okpe',
      'Oshimili north',
      'Oshimili south',
      'Patani',
      'Sapele',
      'Udu',
      'Ughelli south',
      'Ughelli north',
      'Ukwuani',
      'Uviwie',
      'Warri central',
      'Warri north',
      'Warri south'
    ]
  },
  {
    name: 'Ebonyi',
    capital: 'Abakaliki',
    divisions: [
      'Abakaliki',
      'Afikpo south',
      'Afikpo north',
      'Ebonyi',
      'Ezza',
      'Ezza south',
      'Ikwo',
      'Ishielu',
      'Ivo',
      'Ohaozara',
      'Ohaukwu',
      'Onicha',
      'Izzi'
    ]
  },
  {
    name: 'Edo',
    capital: 'Benin',
    divisions: [
      'Akoko-Edo',
      'Egor',
      'Essann east',
      'Esan south east',
      'Esan central',
      'Esan west',
      'Etsako central',
      'Etsako east',
      'Etsako',
      'Orhionwon',
      'Ivia north',
      'Ovia south west',
      'Owan west',
      'Owan south',
      'Uhunwonde'
    ]
  },
  {
    name: 'Ekiti',
    capital: 'Ado Ekiti',
    divisions: [
      'Ado Ekiti',
      'Aiyekire',
      'Effon Alaiye',
      'Ekiti east',
      'Ekiti south west',
      'Ekiti west',
      'Emure/ise',
      'Ido',
      'Ijero',
      'Ikere',
      'Ikole',
      'Ilejemeje',
      'Irepodun',
      'Ise/Orun',
      'Moba',
      'Orun',
      'Osi',
      'Oye'
    ]
  },
  {
    name: 'Enugu',
    capital: 'Enugu',
    divisions: [
      'Aninri',
      'Awgu',
      'Enugu east',
      'Enugu north',
      'Enugu south',
      'Ezeagu',
      'Igbi etiti',
      'Igbo Eze north',
      'Nsukka',
      'Oji river',
      'Udi',
      'Undenu',
      'Uzo Uwani'
    ]
  },
  {
    name: 'Gombe',
    capital: 'Gombe',
    divisions: [
      'Akko',
      'Balanga',
      'Billiri',
      'Dukku',
      'Dunakaye',
      'Gombe',
      'Kaltungo',
      'Kwami',
      'Nafada/Bajoga',
      'Shomgom',
      'Yamaltu/Deba'
    ]
  },
  {
    name: 'Imo',
    capital: 'Owerri',
    divisions: [
      'Aboh-mbaise',
      'Aguta',
      'Ahiazu-Mbaise',
      'Ehime-Mbaino',
      'Ezinhite, Ideato North',
      'Ideato south',
      'Ihitte/Uboma',
      'Ikeduru',
      'Isiala',
      'Isu',
      'Mbaitoli',
      'Ngor Okpala',
      'Njaba',
      'Nkwere',
      'Nwangele',
      'Obowo',
      'Ohaji Egbema',
      'Okigwe',
      'Onuimo',
      'Orlu',
      'Orsu',
      'Oru',
      'Oru west',
      'Owerri',
      'Owerri North',
      'Owerri south'
    ]
  },
  {
    name: 'Jigawa',
    capital: 'Dutse',
    divisions: [
      'Auyo',
      'Babura',
      'Birnin- Kudu',
      'Birnin-magaji',
      'Birniwa',
      'Buji',
      'Dutse',
      'Gagarawa',
      'Garki',
      'Gumel',
      'Guri',
      'Gwaram',
      'Gwiwa',
      'Hadeji',
      'Jahun',
      'Kafin-Hausa',
      'Kazaure',
      'Kirikisamma',
      'Maigatari',
      'Malamaduri',
      'Miga',
      'Ringim',
      'Roni',
      'Sule Tankarka',
      'Taura',
      'Yankwasi',
      'kaugama'
    ]
  },
  {
    name: 'Kaduna',
    capital: 'Kaduna',
    divisions: [
      'Brnin Gwari',
      'Chukun',
      'Giwa',
      'Igabi',
      'Ikara',
      'Jaba',
      'Jema`a',
      'Kabau',
      'Kachia',
      'Kaduna North',
      'Kaduna south',
      'Kagarok',
      'Kajuru',
      'Kauru',
      'Kere',
      'Kudan',
      'Makarfi',
      'Sabongari',
      'Sanga',
      'Soba',
      'Zangon-Kataf',
      'Zaria'
    ]
  },
  {
    name: 'Kano',
    capital: 'Kano',
    divisions: [
      'Ajigi',
      'Albasu',
      'Bagwai',
      'Bebeji',
      'Bichi',
      'Bunkure',
      'Dala',
      'Dambatta',
      'Dawakin kudu',
      'Dawakin tofa',
      'Doguwa',
      'Fagge',
      'Gabasawa',
      'Garko',
      'Garun mallam',
      'Gaya',
      'Gezawa',
      'Gwale',
      'Gwarzo',
      'Kano',
      'Karay',
      'Kibiya',
      'Kiru',
      'Kumbtso',
      'Kunch',
      'Kura',
      'MInjibir Nassarawa',
      'Maidobi',
      'Makoda',
      'Rano',
      'Rimin gado',
      'Rogo',
      'Shanono',
      'Sumaila',
      'Takai',
      'Tarauni',
      'Tofa',
      'Tsanyawa',
      'Tudunwada',
      'Ungogo',
      'Warawa',
      'Wudil'
    ]
  },
  {
    name: 'Katsina',
    capital: 'Katsina',
    divisions: [
      'Bakori',
      'Batagarawa',
      'Batsari',
      'Baure',
      'Bindawa',
      'Charanchi',
      'Dan- Musa',
      'Dandume,Danja',
      'Daura',
      'Dutsi',
      'Dutsin `ma',
      'Faskar',
      'Funtua',
      'Furfi',
      'Ingawa',
      'Jibiya',
      'Kafur',
      'Kaita',
      'Kankara',
      'Kankiya',
      'Katsina',
      'Kusada.Mai aduwa',
      'Malumfashi',
      'Mani',
      'Mash',
      'Matazu',
      'Musawa',
      'Rimi',
      'Sabuwa',
      'Safana',
      'Sandamu',
      'Zango'
    ]
  },
  {
    name: 'Kebbi',
    capital: 'Birnin Kebbi',
    divisions: [
      'Aliero',
      'Arewa Dandi',
      'Argungu',
      'Augie',
      'Bagudo',
      'Birnin Kebbi',
      'Bunza',
      'Dandi',
      'Danko',
      'Fakai',
      'Gwandu',
      'Jeda',
      'Kalgo',
      'Koko-besse',
      'Maiyaama',
      'Ngaski',
      'Sakaba',
      'Shanga',
      'Suru',
      'Wasugu',
      'Yauri',
      'Zuru'
    ]
  },
  {
    name: 'Kogi',
    capital: 'Lokoja',
    divisions: [
      'Adavi',
      'Ajaokuta',
      'Ankpa',
      'Bassa',
      'Dekina',
      'Ibaji',
      'Idah',
      'Igalamela',
      'Ijumu',
      'Kabba bunu',
      'Kogi',
      'Mopa muro',
      'Ofu',
      'Ogori magongo',
      'Okehi',
      'Okene',
      'Olamaboro',
      'Omala',
      'Yagba east',
      'Yagba west'
    ]
  },
  {
    name: 'Kwara',
    capital: 'Ilorin',
    divisions: [
      'Asa',
      'Baruten',
      'Ede',
      'Ekiti',
      'Ifelodun',
      'Ilorin east',
      'Ilorin south',
      'Ilorin west',
      'Irepodun',
      'Isin',
      'Kaiama',
      'Moro',
      'Offa',
      'Oke ero',
      'Oyun',
      'Pategi'
    ]
  },
  {
    name: 'Lagos',
    capital: 'Ikeja',
    divisions: [
      'Agege',
      'Alimosho',
      'Alimosho Ifelodun',
      'Amuwo-Odofin',
      'Apapa',
      'Badagry',
      'Epe',
      'Eti-Osa',
      'Ibeju- Lekki',
      'Ifako/Ijaye',
      'Ikeja',
      'Ikorodu',
      'Kosofe',
      'Lagos Island',
      'Lagos Mainland',
      'Mushin',
      'Ojo',
      'Oshodi-Isolo',
      'Shomolu',
      'Surulere'
    ]
  },
  {
    name: 'Nasarawa',
    capital: 'Lafia',
    divisions: [
      'Akwanga',
      'Awe',
      'Doma',
      'Karu',
      'Keana',
      'Keffi',
      'Kokona',
      'Lafia',
      'Nassarawa',
      'Nassarawa/Eggon',
      'Obi',
      'Toto',
      'Wamba'
    ]
  },
  {
    name: 'Niger',
    capital: 'Minna',
    divisions: [
      'Agaie',
      'Agwara',
      'Bida',
      'Borgu',
      'Bosso',
      'Chanchanga',
      'Edati',
      'Gbako',
      'Gurara',
      'Kitcha',
      'Kontagora',
      'Lapai',
      'Lavun',
      'Magama',
      'Mariga',
      'Mokwa',
      'Moshegu',
      'Muya',
      'Paiko',
      'Rafi',
      'Shiroro',
      'Suleija',
      'Tawa-Wushishi'
    ]
  },
  {
    name: 'Ogun',
    capital: 'Abeokuta',
    divisions: [
      'Abeokuta north',
      'Abeokuta south',
      'Ado-odo/otta',
      'Agbado north',
      'Agbado south',
      'Ewekoro',
      'Idarapo',
      'Ifo',
      'Ijebu east',
      'Ijebu north',
      'Ikenne',
      'Ilugun Alaro',
      'Imeko afon',
      'Ipokia',
      'Obafemi/owode',
      'Odeda',
      'Odogbolu',
      'Ogun waterside',
      'Sagamu'
    ]
  },
  {
    name: 'Ondo',
    capital: 'Akure',
    divisions: [
      'Akoko north',
      'Akoko north east',
      'Akoko south',
      'Akoko south east',
      'Akure',
      'Akure north',
      'Ese odo',
      'Idanre',
      'Ifedore',
      'Ilaje',
      'Ilaje oke-igbo',
      'Irele',
      'Odigbo',
      'Okitipupa',
      'Ondo',
      'Ondo east',
      'Ose',
      'Owo'
    ]
  },
  {
    name: 'Osun',
    capital: 'Oshogbo',
    divisions: [
      'Atakumosa east',
      'Atakumosa west',
      'Ayeda-ade',
      'Ayedire',
      'Bolawaduro',
      'Boripe',
      'Ede',
      'Ede north',
      'Egbedore',
      'Ejigbo',
      'Ife central',
      'Ife east',
      'Ife north',
      'Ife south',
      'Ifedayo',
      'Ifelodun',
      'Ila-orangun',
      'Ilesah east',
      'Ilesha west',
      'Irepodun',
      'Irewole',
      'Isokan',
      'Iwo',
      'Obokun',
      'Odo-otin',
      'Oriade',
      'Orolu',
      'Osogbo',
      'ola oluwa',
      'olorunda'
    ]
  },
  {
    name: 'Oyo',
    capital: 'Ibadan',
    divisions: [
      'Afijio',
      'Akinyele',
      'Atigbo',
      'Attba',
      'Egbeda',
      'Ibadan',
      'Ibadan central',
      'Ibadan north east',
      'Ibadan south east',
      'Ibadan west south',
      'Ibarapa east',
      'Ibarapa north',
      'Ido',
      'Ifedapo',
      'Ifeloju',
      'Irepo',
      'Iseyin',
      'Itesiwaju',
      'Iwajowa',
      'Iwajowa olorunshogo',
      'Kajola',
      'Lagelu',
      'Ogbomosho north',
      'Ogbomosho south',
      'Ogo oluwa',
      'Oluyole',
      'Ona ara',
      'Ore lope',
      'Orire',
      'Oyo east',
      'Oyo west',
      'Saki east',
      'Saki west',
      'Surulere'
    ]
  },
  {
    name: 'Plateau',
    capital: 'Jos',
    divisions: [
      'Barkin/ladi',
      'Bassa',
      'Bokkos',
      'Jos east',
      'Jos north',
      'Jos south',
      'Kanam',
      'Kiyom',
      'Langtang north',
      'Langtang south',
      'Mangu,',
      'Mikang',
      'Pankshin',
      'Qua`an pan',
      'Shendam',
      'Wase'
    ]
  },
  {
    name: 'Rivers',
    capital: 'Port Harcourt',
    divisions: [
      'Abua/Odial',
      'Ahoada west',
      'Akuku toru',
      'Andoni',
      'Asari toru',
      'Bonny',
      'Degema',
      'Eleme',
      'Emohua',
      'Etche',
      'Gokana',
      'Ikwerre',
      'Khana',
      'Obio/Akpor',
      'Ogba east /Edoni',
      'Ogu/bolo',
      'Okrika',
      'Omumma',
      'Opobo/Nkoro',
      'Oyigbo',
      'Portharcourt',
      'Tai'
    ]
  },
  {
    name: 'Sokoto',
    capital: 'Sokoto',
    divisions: [
      'Binji',
      'Bodinga',
      'Dange/shuni',
      'Gada',
      'Goronyo',
      'Gudu',
      'Gwadabawa',
      'Illela',
      'Kebbe',
      'Kware',
      'Rabah',
      'Sabon-Birni',
      'Shagari',
      'Silame',
      'Sokoto north',
      'Sokoto south',
      'Tambuwal',
      'Tangaza',
      'Tureta',
      'Wamakko',
      'Wurno',
      'Yabo'
    ]
  },
  {
    name: 'Taraba',
    capital: 'Jalingo',
    divisions: [
      'Akdo-kola',
      'Bali',
      'Donga',
      'Gashaka',
      'Gassol',
      'Ibi',
      'Jalingo',
      'K/Lamido',
      'Kurmi',
      'Sardauna',
      'Tarum',
      'Ussa',
      'Wukari',
      'Yorro',
      'Zing',
      'lan'
    ]
  },
  {
    name: 'Yobe',
    capital: 'Damaturu',
    divisions: [
      'Borsari',
      'Damaturu',
      'Fika',
      'Fune',
      'Gashua',
      'Geidam',
      'Gogaram',
      'Gujba',
      'Gulani',
      'Jakusko',
      'Karasuwa',
      'Machina',
      'Nagere',
      'Nguru',
      'Potiskum',
      'Tarmua',
      'Yunusari',
      'Yusufari'
    ]
  },
  {
    name: 'Zamfara',
    capital: 'Gusau',
    divisions: [
      'Anka',
      'Bukkuyum',
      'Chafe',
      'Dungudu',
      'Gummi',
      'Gusau',
      'Isa',
      'Kaura Namoda',
      'Maru',
      'Mradun',
      'Shinkafi',
      'Talata Mafara',
      'Zumi'
    ]
  },
  {
    name: 'FCT Abuja',
    capital: 'Abuja',
    divisions: [
      'Abaji',
      'Abuja Municipal',
      'Bwari',
      'Gwagwalada',
      'Kuje',
      'Kwali'
    ]
  }
];

function getStates() {
  return states;
}

function getState(state) {
  return states.find(
    (item) => item.state.toLowerCase() === state.toLowerCase()
  );
}
// module.exports = getStates;
// exports = getStates;
module.exports = {
  getState,
  getStates
};
